language: xml

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

install:
  - sudo apt-get update -q
  - sudo apt-get install xsltproc
  - sudo apt-get install docbook
  - sudo apt-get install docbook-xml docbook-xsl
  - sudo apt-get install dblatex
  - sudo apt-get install texlive-lang-european
  - sudo apt-get install make
  - sudo apt-get install pkg-config
  - sudo apt-get install graphviz
  - sudo apt-get install libxml2-utils
  - sudo apt-get install imagemagick

script: make
