language: xml

install:
  - sudo apt-get update -q
  - sudo apt-get install xsltproc
  - sudo apt-get install docbook
  - sudo apt-get install docbook-xml docbook-xsl
  - sudo apt-get install dblatex
  - sudo apt-get install texlive-lang-european
  - sudo apt-get install make
  - sudo apt-get install pkg-config
  - sudo apt-get install graphviz
  - sudo apt-get install xmllint
  - sudo apt-get install imagemagick

script: make
