language: xml
script: make

addons:
  apt:
    packages:
      - docbook
      - docbook-xml
      - docbook-xsl
      - dblatex
      - texlive-lang-european
      - make
      - pkg-config
      - xsltproc
      - graphviz
      - xmllint
