branches:
  only:
  - master
language: xml
before_install:
- wget -qq -O - https://www.mongodb.org/static/pgp/server-3.2.pub | sudo apt-key add -
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
- sudo apt-get update
install:
- sudo sh ./scripts/build_ubuntu
- curl -L https://git.io/fhj4c | sudo bash
script: make
before_deploy:
- git config --local user.name "krook1024"
- git config --local user.email "krook1024@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "bdkMfKFDXsdbfOckRWwNSm/8FFfKbBpxGRUtPz5VAv/WCjWjpM/xyyVoENTj1kNbkM5aFF5OEZK6CQJRiv1IQFL97hWN6eCR2E9/Ng9all6Aw/uXUZGAcnCYlG1r2jo+gCtjNxQQMSg9h7BDuV4Qfs961ZCuXFy8wkooTCTv9s5LNE8WPns8IOlUQO6zvsvFewFe5+DhlvHlL7c5VdtKuQ9FMbkuj9mOYz1EzessixAOMh5LZlnJ6IRpjRb3a25LEkJFl9PHOXiTx0gdZngPM+aPC+YXj41t886NhtmhbH1DWg44W3pjtVNQMYMQ0rSzAWkidXz2icnt8gnY5eObdfib36XKwVz1MDcQ/v2iQitYCswJ6Y3/M9yExjoPzXA+e+dtvnblMRo27HrnCImegwZfqul9vCACIr1wIfDkvqYn951J1PgfrSRNW5jlmhBcGayAcWjJyhtYPbefiWuZT4OlEJqKNARVvONJ7jhlnoLYe9yEA0l4AN/RE4OK2YU6UVcvjwhQX2NPXlRHyLjGtrIL0KjnldmXnnr9FxnD5+0cRztYSdHW9tNMxARvv4ImxTj90XYgp2gOQvywAPicikqI+paYWCeVe0rmKSjsOBC/mheGOT0EgkoK/6ef3gvrMdpT/PR+d7NmnC9Wg+sxJex7/Ep+W0XZqeIksOpZIDA="
  file: tb-fdl.pdf
  on:
    repo: krook1024/textbook
  skip_cleanup: true
  prerelease: true
