branches:
  only:
  - master
language: xml
before_install:
- wget -q -O - https://www.mongodb.org/static/pgp/server-3.2.pub | sudo apt-key add -
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- sudo apt-get update -q
install:
- sudo apt-get install -y make
- sudo apt-get install -y xsltproc
- sudo apt-get --no-install-recommends install docbook docbook-xml docbook-xsl dblatex texlive-base texlive-binaries texlive-latex-base texlive-fonts-recommended texlive-latex-recommended texlive-lang-european
- sudo apt-get install -y graphviz libxml2-utils
- sudo apt-get install -y curl
- curl -L https://git.io/fhj4c | sudo bash
script: make
before_deploy:
- git config --local user.name "krook1024"
- git config --local user.email "krook1024@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "KiRsBq/ETH2mg0qcHvyfmI7VwFuphz5/8SfubzTW1TXxRdAsaXG8h93B51OjAbUWOmcsz4uLwrqNfVR6OwN1n8Wq2b1Qqba3/V9S2LHHxNwm9U1jaNfCMnEgk1UCFlFDjIlsjUmKvQXHakJENL6TC49dZe5XkOUVd5urRDwrzNIOqfnVdxpe9wCIHSoShlKIRCbFExHwQ/IUiSeVZJLbDwkqwUG2y0AWcb1nID2XzZgtE1kwPo8hSTC7T4uqi0dXBC0u8eqpK3IGl1C0KROWxsaRJgIHMx65SLV4SxyDneJZMsJAKiaylOUVPPYTp4186oCP4qECoH6BURiTr42mN06cfu3qaH+bN1ZLwgLbRfGiZTCewGyHZbBeLmM6xtU5E3/uH2/qMSuTRn8t9/fJcynrVfVA+OSJyb0lDOIgFyzsatd7qaM7DgQUmgDwrztVBoEVuehfBHxaFt1LaH0Gxcf9xHh9XqaY+7ZBuPUsiQowCkfxdvDjKuCQVm1n81BfuxrwqIpg9eWMkIy25R63aE7XJEwzHprZyFek2d/QBCxsiDyHfxfuXT2idZwGkJRC1L80ahrE0N00yTezkgaYQuevLswUk77hb941KwAke9Md3hXy48GkJbxesevIYMaOQ4P3CaezntHjruJKElhry18vGnj0340mH+9i1Y4KDro="
  file: tb-fdl.pdf
  on:
    repo: krook1024/textbook
  skip_cleanup: true
  prerelease: true
