#!/usr/bin/env sh

dir=$(mktemp -d)
cp './*' $dir/ >/dev/null 2>&1
cd $dir || echo "Failed to create temporary directory!"
qmake . >/dev/null 2>&1
make >/dev/null 2>&1
./Sejtauto >/dev/null 2>&1
rm -rf $dir >/dev/null 2>&1
