######################################################################
# Automatically generated by qmake (3.0) Sun Mar 30 12:06:07 2014
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Sejtauto
INCLUDEPATH += .

# Input
HEADERS += sejtablak.h sejtszal.h
SOURCES += main.cpp sejtablak.cpp sejtszal.cpp
